services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex 
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 32400:32400/tcp    # Plex remote & web
    devices:
     - /dev/dri:/dev/dri # QuickSync
    volumes:
      - ${PLEX_CONFIG_HOME}/plex/config:/config
      - ${PLEX_DATA_HOME}/media:/data
    networks:
      proxy: {}                 # join the external proxy network
      servarrnetwork:           # join the internal network with static IP
        ipv4_address: 10.99.0.10
      
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    hostname: overseerr 
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    # Don't bind Overseerr directly to the host when using cloudflared tunnel.
    # cloudflared will route traffic to the container over the internal Docker network.
    volumes:
      - ${PLEX_CONFIG_HOME}/overseerr/config:/app/config
    restart: unless-stopped
    networks:
      - proxy
      - servarrnetwork

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${PLEX_CONFIG_HOME}/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    networks:
      - proxy

  

networks:
  proxy:
    driver: bridge
  servarrnetwork:
    external: true

