services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
        - ${FILEBROWSER_DATA}:/srv
        - ${FILEBROWSER_DATABASE}:/database
        - ${FILEBROWSER_CONFIG}:/config
    ports:
        - 8123:80

    networks:
      - proxy
      - admin_net

networks:
  proxy:
    external: true
  admin_net:
    driver: bridge