services:
  glance:
    container_name: glance
    image: glance-app/glance:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    env_file: .env

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    volumes:
        - filebrowser_data:/srv
        - filebrowser_database:/database
        - filebrowser_config:/config
    ports:
        - 8123:80
